name: mlenv
channels:
  - conda-forge
  - auto
  - defaults
dependencies:
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py_0
  - bleach=3.1.0=py_0
  - ca-certificates=2019.9.11=hecc5488_0
  - certifi=2019.9.11=py37_0
  - colorama=0.4.1=py_0
  - cycler=0.10.0=py_2
  - cython=0.29.13=py37h6538335_0
  - decorator=4.4.1=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py37_1000
  - freetype=2.10.0=h563cfd7_1
  - icu=64.2=he025d50_1
  - importlib_metadata=0.23=py37_0
  - ipykernel=5.1.3=py37h5ca1d4c_0
  - ipython=7.9.0=py37h5ca1d4c_0
  - ipython_genutils=0.2.0=py_1
  - jedi=0.15.1=py37_0
  - jinja2=2.10.3=py_0
  - joblib=0.14.0=py_0
  - jpeg=9c=hfa6e2cd_1001
  - json5=0.8.5=py_0
  - jsonschema=3.1.1=py37_0
  - jupyter_client=5.3.3=py37_1
  - jupyter_core=4.5.0=py_0
  - jupyterlab=1.1.4=py_0
  - jupyterlab_server=1.0.6=py_0
  - kiwisolver=1.1.0=py37he980bc4_0
  - libblas=3.8.0=14_mkl
  - libcblas=3.8.0=14_mkl
  - libclang=9.0.0=h74a9793_1
  - liblapack=3.8.0=14_mkl
  - liblapacke=3.8.0=14_mkl
  - libopencv=4.1.2=h7e61296_0
  - libpng=1.6.37=h7602738_0
  - libsodium=1.0.17=h2fa13f4_0
  - libtiff=4.1.0=h2e92f26_0
  - libwebp=1.0.2=hfa6e2cd_2
  - lz4-c=1.8.3=he025d50_1001
  - markupsafe=1.1.1=py37hfa6e2cd_0
  - matplotlib=3.1.1=py37_1
  - matplotlib-base=3.1.1=py37h2852a4a_1
  - mistune=0.8.4=py37hfa6e2cd_1000
  - mkl-service=2.3.0=py37hfa6e2cd_0
  - more-itertools=7.2.0=py_0
  - nbconvert=5.6.1=py37_0
  - nbformat=4.4.0=py_1
  - notebook=6.0.1=py37_0
  - numpy=1.17.3=py37hc71023c_0
  - opencv=4.1.2=0
  - openssl=1.1.1d=hfa6e2cd_0
  - pandas=0.25.2=py37he350917_0
  - pandoc=2.7.3=0
  - pandocfilters=1.4.2=py_1
  - parso=0.5.1=py_0
  - patsy=0.5.1=py_0
  - pickleshare=0.7.5=py37_1000
  - pip=19.3.1=py37_0
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=2.0.10=py_0
  - py-opencv=4.1.2=py37h5ca1d4c_0
  - pygments=2.4.2=py_0
  - pyparsing=2.4.2=py_0
  - pyqt=5.12.3=py37h6538335_0
  - pyrsistent=0.15.4=py37hfa6e2cd_0
  - python=3.7.3=h510b542_1
  - python-dateutil=2.8.0=py_0
  - pytz=2019.3=py_0
  - pywin32=224=py37hfa6e2cd_1000
  - pywinpty=0.5.5=py37_1000
  - pyzmq=18.1.0=py37h16f9016_0
  - qt=5.12.5=h7ef1ec2_0
  - scikit-learn=0.21.3=py37h7208079_0
  - seaborn=0.9.0=py_1
  - send2trash=1.5.0=py_0
  - setuptools=41.4.0=py37_0
  - six=1.12.0=py37_1000
  - sqlite=3.30.1=hfa6e2cd_0
  - statsmodels=0.10.1=py37hfa6e2cd_0
  - terminado=0.8.2=py37_0
  - testpath=0.4.2=py_1001
  - textdistance=4.1.3=py_0
  - tornado=6.0.3=py37hfa6e2cd_0
  - traitlets=4.3.3=py37_0
  - wcwidth=0.1.7=py_1
  - webencodings=0.5.1=py_1
  - wheel=0.33.6=py37_0
  - wincertstore=0.2=py37_1002
  - winpty=0.4.3=4
  - xlsxwriter=1.2.6=py_0
  - xz=5.2.4=h2fa13f4_1001
  - zeromq=4.3.2=h6538335_2
  - zipp=0.6.0=py_0
  - zlib=1.2.11=h2fa13f4_1006
  - zstd=1.4.3=hd8a0e53_0
  - blas=1.0=mkl
  - icc_rt=2019.0.0=h0cc432a_1
  - intel-openmp=2019.4=245
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - mkl=2019.4=245
  - msys2-conda-epoch=20160418=1
  - scipy=1.3.1=py37h29ff71c_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_0
  - pip:
    - pyqt5==5.12.3
    - pyqt5-sip==4.19.18
    - pyqtwebengine==5.12.1
prefix: C:\Anaconda3\envs\mlenv

